import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" w-screen text-white bg-black font-inter">
        <SessionWrapper>
          <Navbar />
          <Toaster />
          <div className="mt-24"></div>
          <main>{children}</main>
        </SessionWrapper>
      </body>

    </html>
  );
}
